// Code generated by goyacc -o parser.go expr.y. DO NOT EDIT.

//line expr.y:3
package ast

import __yyfmt__ "fmt"

//line expr.y:3

import ()

const IDENT = 57346
const NUMBER = 57347
const STRING = 57348
const BOOL = 57349
const NIL = 57350
const EQ = 57351
const AND = 57352
const OR = 57353
const NOTEQ = 57354
const GT = 57355
const GTE = 57356
const LT = 57357
const LTE = 57358
const ORR = 57359
const ACC = 57360
const UMINUS = 57361

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"NUMBER",
	"STRING",
	"BOOL",
	"NIL",
	"EQ",
	"AND",
	"OR",
	"NOTEQ",
	"GT",
	"GTE",
	"LT",
	"LTE",
	"ORR",
	"ACC",
	"'='",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'&'",
	"'|'",
	"'?'",
	"':'",
	"'!'",
	"'^'",
	"UMINUS",
	"'('",
	"')'",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line expr.y:80

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 228

var yyAct = [...]int8{
	2, 60, 59, 55, 54, 32, 33, 6, 1, 0,
	0, 0, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 56, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 28, 12, 13, 14, 15, 17, 18,
	29, 0, 0, 16, 16, 0, 57, 0, 0, 61,
	30, 62, 19, 20, 21, 22, 23, 24, 25, 26,
	27, 28, 31, 12, 13, 14, 15, 17, 18, 29,
	58, 0, 16, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 0, 12, 13, 14, 15, 17, 18,
	29, 0, 0, 16, 19, 20, 21, 22, 23, 24,
	25, 26, 0, 28, 0, 12, 13, 14, 15, 17,
	18, 29, 0, 0, 16, 19, 20, 21, 22, 23,
	24, 25, 26, 0, 28, 0, 0, 0, 14, 15,
	17, 18, 29, 0, 0, 16, 19, 20, 21, 22,
	23, 24, 25, 26, 0, 28, 0, 0, 0, 0,
	0, 17, 18, 29, 0, 0, 16, 19, 20, 21,
	22, 23, 24, 25, 26, 0, 28, 0, 0, 3,
	7, 9, 8, 10, 29, 0, 0, 16, 19, 20,
	21, 22, 23, 24, 25, 26, 5, 28, 0, 0,
	0, 0, 0, 4, 0, 0, 11, 19, 16, 0,
	22, 23, 24, 25, 26, 0, 28, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 16,
}

var yyPact = [...]int16{
	175, -1000, 74, 41, 175, 175, -1000, -1000, -1000, -1000,
	-1000, 175, 175, 175, 175, 175, 175, 175, 175, 175,
	175, 175, 175, 175, 175, 175, 175, 175, 175, 175,
	175, 175, 25, -1000, 24, 116, 116, 137, 137, 25,
	158, 158, 25, 198, 198, 25, 25, 25, 25, 25,
	95, -1000, 53, 74, -30, -32, 74, -1000, 175, -1000,
	175, 179, 74,
}

var yyPgo = [...]int8{
	0, 8, 0, 7, 4, 3,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 4, 4, 5, 5,
}

var yyR2 = [...]int8{
	0, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 2, 5, 1, 1, 1, 1, 1, 1, 4,
	3, 0, 1, 1, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, 4, 28, 21, -3, 5, 7, 6,
	8, 31, 20, 21, 22, 23, 29, 24, 25, 9,
	10, 11, 12, 13, 14, 15, 16, 17, 18, 26,
	19, 31, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -4, -5, -2, 32, 27, 32,
	33, -2, -2,
}

var yyDef = [...]int8{
	0, -2, 1, 28, 0, 0, 23, 24, 25, 26,
	27, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 31, 20, 21, 0, 2, 3, 4, 5, 6,
	7, 8, 9, 11, 12, 13, 14, 15, 16, 17,
	18, 19, 0, 10, 0, 32, 33, 30, 0, 29,
	0, 22, 34,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 28, 3, 3, 3, 3, 24, 3,
	31, 32, 22, 20, 33, 21, 3, 23, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 27, 3,
	3, 19, 3, 26, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 29, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 25,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 30,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:29
		{
			yylex.(Setter).SetRoot(yyS[yypt-0].node)
			yyVAL.node = yyS[yypt-0].node
		}
	case 2:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:33
		{
			yyVAL.node = &Binary{Op: "+", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:34
		{
			yyVAL.node = &Binary{Op: "-", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:35
		{
			yyVAL.node = &Binary{Op: "*", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:36
		{
			yyVAL.node = &Binary{Op: "/", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:37
		{
			yyVAL.node = &Binary{Op: "^", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:38
		{
			yyVAL.node = &Binary{Op: "&", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:39
		{
			yyVAL.node = &Binary{Op: "|", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:40
		{
			yyVAL.node = &Binary{Op: "==", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:41
		{
			yyVAL.node = &Set{L: yyS[yypt-2].str, R: yyS[yypt-0].node}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:42
		{
			yyVAL.node = &Binary{Op: "&&", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:43
		{
			yyVAL.node = &Binary{Op: "||", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:44
		{
			yyVAL.node = &Binary{Op: "!=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:45
		{
			yyVAL.node = &Binary{Op: ">", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:46
		{
			yyVAL.node = &Binary{Op: ">=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:47
		{
			yyVAL.node = &Binary{Op: "<", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:48
		{
			yyVAL.node = &Binary{Op: "<=", L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:49
		{
			yyVAL.node = &Call{Name: "orr", Args: []Node{yyS[yypt-2].node, yyS[yypt-0].node}}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:50
		{
			yyVAL.node = &Access{L: yyS[yypt-2].node, R: yyS[yypt-0].node}
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:51
		{
			yyVAL.node = &Unary{Op: "!", X: yyS[yypt-0].node}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expr.y:52
		{
			yyVAL.node = &Unary{Op: "-", X: yyS[yypt-0].node}
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expr.y:53
		{
			yyVAL.node = &Call{Name: "ternary", Args: []Node{yyS[yypt-4].node, yyS[yypt-2].node, yyS[yypt-0].node}}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:54
		{
			yyVAL.node = yyS[yypt-0].node
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:59
		{
			yyVAL.node = &Number{Val: yyS[yypt-0].num}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:60
		{
			yyVAL.node = &Bool{Val: yyS[yypt-0].boolean}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:61
		{
			yyVAL.node = &String{Val: yyS[yypt-0].str}
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:62
		{
			yyVAL.node = &Nil{}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:63
		{
			yyVAL.node = &Variable{Name: yyS[yypt-0].str}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expr.y:64
		{
			yyVAL.node = &Call{Name: yyS[yypt-3].str, Args: yyS[yypt-1].nodes}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:65
		{
			yyVAL.node = yyS[yypt-1].node
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expr.y:71
		{
			yyVAL.nodes = nil
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:72
		{
			yyVAL.nodes = yyS[yypt-0].nodes
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expr.y:76
		{
			yyVAL.nodes = []Node{yyS[yypt-0].node}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expr.y:77
		{
			yyVAL.nodes = append(yyS[yypt-2].nodes, yyS[yypt-0].node)
		}
	}
	goto yystack /* stack new state and value */
}
